"""Generate docs/builder/languages.js from src/enrichment/languages.py (single source of truth).

Usage: python scripts/gen_languages_js.py          # rewrite the file
       python scripts/gen_languages_js.py --check  # exit 1 if it is out of date
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.enrichment.languages import ALIASES, CANONICAL  # noqa: E402

OUT = ROOT / "docs" / "builder" / "languages.js"


def render() -> str:
    canonical = json.dumps(list(CANONICAL), ensure_ascii=False)
    aliases = ",\n".join(
        f"    {json.dumps(k, ensure_ascii=False)}: {json.dumps(v, ensure_ascii=False)}"
        for k, v in ALIASES.items()
    )
    return (
        "// GENERATED by scripts/gen_languages_js.py from src/enrichment/languages.py. Do not edit.\n"
        "(function (root) {\n"
        "  'use strict';\n"
        f"  var CANONICAL = {canonical};\n"
        "  var ALIASES = {\n"
        f"{aliases}\n"
        "  };\n"
        "  function normalize(value) {\n"
        "    if (typeof value !== 'string') return null;\n"
        "    var key = value.trim().toLowerCase();\n"
        "    return Object.prototype.hasOwnProperty.call(ALIASES, key) ? ALIASES[key] : null;\n"
        "  }\n"
        "  root.SpotiLang = { CANONICAL: CANONICAL, ALIASES: ALIASES, normalize: normalize };\n"
        "})(typeof window !== 'undefined' ? window : globalThis);\n"
    )


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = OUT.read_bytes().decode("utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is out of date; run python scripts/gen_languages_js.py")
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_bytes(text.encode("utf-8"))
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
